version: "1.0"
services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: 'postgres-core'
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  CoreSystemNetwork:
    name: core-system-network

volumes:
  rabbitmq:
    driver: local
  postgres:
    driver: local
 
  